### ISSUE TITLE
Portfolio store

### ISSUE THREAD

**Issue by youaresofunny** [TrustyFund/vuex-bitshares#3]
Портфель - balances пользователя, представленные в следующем виде:
portfolio: [
 {asset_id,asset_symbol,amount,base_value,usd_value,share,future_share,base_change,usd_change}
 ...
]

Учесть, что у нас есть набор стандартных ассетов, которые должны по умолчанию показывать в портфеле.

В идеале посмотреть, как это реализовано в react версии (portfolioStore, portfolioActions) и предложить более лучший вариант.

**Comment by roma219** [comment]
@youaresofunny https://github.com/TrustyFund/vuex-bitshares/pull/5

**Comment by youaresofunny** [comment]
:+1:
