### ISSUE TITLE
Некорректная работа функции calcPortfolioDistributionChange

### ISSUE THREAD

**Issue by roma219** [TrustyFund/vuex-bitshares#31]
Входные данные:
![image](https://user-images.githubusercontent.com/4411295/37330390-e1515c0c-26db-11e8-8571-c007f627f522.png)

![image](https://user-images.githubusercontent.com/4411295/37330418-fc9ece72-26db-11e8-8650-4f975c28ad4b.png)

Возвращает:
![image](https://user-images.githubusercontent.com/4411295/37330444-1287beba-26dc-11e8-8b3a-ec5627ba488c.png)

**Comment by michaelenco** [comment]
https://github.com/TrustyFund/vuex-bitshares/commit/0e1f566cb8e4641f7479c423915b2079c2a22387
