### ISSUE TITLE
Некорректная работа функции distributionSampling

### ISSUE THREAD

**Issue by roma219** [TrustyFund/vuex-bitshares#32]
accuracy = 3

![image](https://user-images.githubusercontent.com/4411295/37331511-1a662790-26df-11e8-9d4d-6e5b2a0f4b39.png)

**Comment by michaelenco** [comment]
https://github.com/TrustyFund/vuex-bitshares/commit/3ef05465258a05d0c47fd076d475b5e6e9f739ab

**Comment by michaelenco** [comment]
Просьба в следующий раз текстовые данные отправлять в текстовом виде.

**Comment by roma219** [comment]
@michaelenco 
Входные данные:
"{"1.3.0":0.5700268982667804,"1.3.113":0.10582752186532557,"1.3.121":0.000043214634294735743,"1.3.850":0,"1.3.858":0,"1.3.861":0.00006169457659182669,"1.3.943":0,"1.3.973":0.06378792759388024,"1.3.1042":0.00011144826739168692,"1.3.1093":0,"1.3.1362":0,"1.3.1578":0.26011570718332416,"1.3.1893":0,"1.3.1999":0.00002558761241135669,"1.3.3128":0,"1.3.2001":0,"1.3.859":0,"1.3.2379":0}"
и accuracy: 2

Выдаёт:
"{"1.3.113":0.1,"1.3.973":0.06,"1.3.1578":0.26,"1.3.1042":0,"1.3.861":0,"1.3.121":0,"1.3.0":0.5700000000000001,"1.3.1999":0,"1.3.858":0,"1.3.2379":0,"1.3.1362":0,"1.3.943":0,"1.3.1893":0,"1.3.850":0,"1.3.3128":0,"1.3.2001":0,"1.3.859":0,"1.3.1093":0}"

![image](https://user-images.githubusercontent.com/4411295/37502714-51c225e0-290f-11e8-98ed-9ad1d45cf69a.png).
Не очень похоже на accuracy 2 да и суммы 100 как бы нет. Просьба тестировать функции прежде чем в мастер лить - точнее никаких коммитов в мастер вообще не должно быть, только PR.
