### ISSUE TITLE
Возможность коннектиться к разным маркетам

### ISSUE THREAD

**Issue by youaresofunny** [TrustyFund/vuex-bitshares#59]
Сейчас service market работает как singleton (export default new Market('1.3.0'))

Нужно:
Возвращать объект где ключ это base asset, а значение - экземпляр в маркете.

Тогда в modules обойдёмся малой кровью:

API.Market['1.3.0'].subscribeToExchangeRate...
API.Market['1.3.0'.unsubscribeFromExchangeRate

И на экране мануальных ордеров будем забирать стакан из выбранной базы путем подписывания на нужный ассет.

TODO:
- [x] Поправить services/market чтобы на выходе был объект с синглтонами
- [x] Поправить места которые использовали этот маркет, чтобы они обращались к BTS

**Comment by roma219** [comment]
Не уверен, что стоит таким громоздким способом это делать. Для начала надо понять, а какие сценарии использования других маркетов предполагаются? Необходима ли возможность использования двух маркетов одновременно?

**Comment by youaresofunny** [comment]
@roma219 необходима, когда юзер будет торговать на manual табе, в фоне будет висеть BTS Market.

**Comment by roma219** [comment]
@youaresofunny что?

**Comment by youaresofunny** [comment]
"Необходима ли возможность использования двух маркетов одновременно?" - да

**Comment by roma219** [comment]
@youaresofunny Ок, это гораздо большая задача, чем просто в API.Market сделать объект с маркетами... Есть подводные камни и в количестве. Думаю целесообразно сначала сделать мануал таб чисто для bts маркета (держа в уме будущее возможность его замены), а далее уже внедрять возможность изменения - тогда и я ясно будет, в какой форме это лучше будет делать.

**Comment by youaresofunny** [comment]
Мануал trading и vuex под него будут в другом issue.
Конкретно здесь все ок - малыми силами расширили service для работы с любым маркетом.

**Comment by roma219** [comment]
А зачем сейчас нужно это расширение? Если его использование предполагается только в модуле manual. Да и реализовать сейчас лучше как:

`const baseMarket = API.Market.getMarket('1.3.0')`
один раз вверху после импорта API

а не городить в каждом модуле API.Market['1.3.0']

**Comment by youaresofunny** [comment]
const baseMarket = API.Market['1.3.0']

**Comment by youaresofunny** [comment]
https://github.com/TrustyFund/vuex-bitshares/pull/60
