### ISSUE TITLE
Перевести тесты wallet'а на mock

### ISSUE THREAD

**Issue by roma219** [TrustyFund/vuex-bitshares#7]
Необходимо сделать так, чтобы тесты модуля Wallet не имели зависимостей по запросам ко внешним API. Для этого необходимо сделать mock сервиса wallet и переписать тесты с использованием его. (см. https://facebook.github.io/jest/docs/en/manual-mocks.html и services/__mocks__/assets.js (мок сервиса работы с ассетами)).

В дальнейшем будут сделаны integration тесты, которые раз в сутки будут проверять корректность этих моков (сравнивать то, что выдают реальный и мокнутый сервисы).

**Comment by michaelenco** [comment]
#9
