### ISSUE TITLE
Api - connection service 

### ISSUE THREAD

**Issue by youaresofunny** [TrustyFund/vuex-bitshares#8]
Нужен сервис, который будет отвечать за подключение к ближайшей ws ноде bitshares.
Список нод можно посмотреть здесь: https://github.com/bitshares/bitshares-ui/blob/staging/app/api/apiConfig.js

Предлагаю в фоне собирать пинги (после подключения к дефолтной ноде), а при следующем подключении (или дисконнекте) подключаться к ближайшей из заполненного пингами списка.

Там сейчас крайне нестабильная ситуация с нодами (в плане аптайма), за сим нужно периодически пинги обновлять (вероятно раз за сессию) и переформировывать список.

**Comment by roma219** [comment]
https://github.com/TrustyFund/vuex-bitshares/pull/12
https://github.com/TrustyFund/trusty-ui-vue/pull/35
